// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

/**
 * notion API Client
 * =========================
 *
 * Matches the OpenAPI specification. All functions are async and return
 * data or `null` on failure.
 *
 * Usage:
 *   import './api.js';        // or <script src="api.js"></script>
 *   const result = await window.API.getPage(id);
 *   const result = await window.API.getBlocks(id);
 *
 * Environment:
 *   Set `window.ENV = 'development'` to enable mocking via /mocks.json.
 *   Set `window.ENV = 'production'` (or anything else) to use real API calls.
 */

const API_BASE = "https://api.notion.com/v1";
const TIMEOUT = 4000;

// ====================== ENVIRONMENT ======================
// Change this to 'production' when connecting to a real backend
window.ENV = "development"; // ← Set to 'production' for real API calls

// Cache for mocks (loaded once)
let mocks = null;
let mocksPromise = null;

async
function loadMocks() {
    if (mocks) return mocks;
    if (mocksPromise) return mocksPromise;

    mocksPromise = fetch("/mocks.json")
        .then((res) => {
            if (!res.ok) throw new Error(`Failed to load mocks.json: ${res.status}`);
            return res.json();
        })
        .then((data) => {
            mocks = Array.isArray(data) ? data : [];
            console.log(
                `%c[Mock] Loaded ${mocks.length} mock(s)`,
                "color: #10b981; font-weight: bold",
            );
            return mocks;
        })
        .catch((err) => {
            console.error("[Mock] Failed to load mocks.json", err);
            mocks = [];
            return [];
        });

    return mocksPromise;
}

function matchesRequest(mockRequest, method, path) {
    if (!mockRequest) return false;

    const mockMethod = mockRequest.method ? .toUpperCase();
    const mockUrl = mockRequest.url;

    if (mockMethod && mockMethod !== method) return false;

    if (mockUrl === path) return true;

    try {
        const mockPath = new URL(mockUrl).pathname;
        return mockPath === path;
    } catch {
        return mockUrl.endsWith(path) || mockUrl === path;
    }
}

async
function apiFetch(path, options = {}) {
    const {
        method = "GET"
    } = options;

    // ====================== DEVELOPMENT MOCKING ======================
    if (window.ENV === "development") {
        await loadMocks();

        const mockEntry = mocks.find((m) =>
            matchesRequest(m.request, method, path),
        );

        if (mockEntry ? .response) {
            const {
                statusCode = 200, body
            } = mockEntry.response;

            console.log(
                `%c[Mock] ${method} ${path} → ${statusCode}`,
                "color: #10b981; font-weight: 600",
            );

            if (statusCode >= 400) {
                console.warn(`[Mock] Error ${statusCode} for ${path}`);
                return null;
            }

            return typeof body === "object" && body !== null ? structuredClone(body) : body;
        }

        console.warn(
            `%c[Mock] No mock found for ${method} ${path}`,
            "color: #f59e0b",
        );
        return null;
    }

    // ====================== REAL API CALL ======================
    const ctrl = new AbortController();
    const timeoutId = setTimeout(() => ctrl.abort(), TIMEOUT);

    try {
        const res = await fetch(API_BASE + path, {
            ...options,
            signal: ctrl.signal,
                headers: {
                    "Content-Type": "application/json",
                    ...options.headers,
                },
        });

        clearTimeout(timeoutId);

        if (!res.ok) {
            console.warn(`API Error: ${res.status} ${path}`);
            return null;
        }

        return await res.json();
    } catch (err) {
        clearTimeout(timeoutId);
        if (err.name === "AbortError") {
            console.error(`Request timeout: ${path}`);
        } else {
            console.error(`Request failed: ${path}`, err);
        }
        return null;
    }
}

// ====================== PUBLIC API ======================

window.API = {
    // GET /pages/{id}
    // Retrieve a Page
    getPage: (id) => apiFetch(`/pages/${id}`),
    // GET /blocks/{id}/children
    // Retrieve block children
    getBlocks: (id, params = {}) => {
        const q = new URLSearchParams();
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        return apiFetch(`/blocks/${id}/children?${q}`);
    },
};