// This file provides tests for the client.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package notion

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"maps"
	"net/http"
	"net/http/httptest"
	"net/url"
	"slices"
	"testing"

	"github.com/MarkRosemaker/openapi-enrich/cassette"
	"github.com/go-api-libs/api"
	"github.com/google/uuid"
)

func newTestServer(t *testing.T, status int) *httptest.Server {
	t.Helper()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(status)
	}))
	t.Cleanup(srv.Close)
	return srv
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(r *http.Request) (*http.Response, error) {
	return f(r)
}

func TestClient_Error(t *testing.T) {
	t.Run("GetPage", func(t *testing.T) {
		t.Setenv("NOTION_API_KEY", "**************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetPage(t.Context(), uuid.Nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetPage(t.Context(), uuid.Nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownStatusCode) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownStatusCode, err)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetPage(t.Context(), uuid.Nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetPage(t.Context(), uuid.Nil); err == nil {
				t.Fatal("expected error")
			}
		})
	})

	t.Run("GetBlocks", func(t *testing.T) {
		t.Setenv("NOTION_API_KEY", "**************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBlocks(t.Context(), uuid.Nil, nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBlocks(t.Context(), uuid.Nil, nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownStatusCode) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownStatusCode, err)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBlocks(t.Context(), uuid.Nil, nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBlocks(t.Context(), uuid.Nil, nil); err == nil {
				t.Fatal("expected error")
			}
		})
	})
}

func replay(t *testing.T) http.RoundTripper {
	t.Helper()

	interactions, err := cassette.InteractionsReadFile("../../api/interactions.json")
	if err != nil {
		t.Fatal(err)
	}

	var idx int
	return roundTripFunc(func(req *http.Request) (*http.Response, error) {
		if idx >= len(interactions) {
			return nil, fmt.Errorf("unexpected request: %s %s", req.Method, req.URL)
		}

		ia := interactions[idx]

		r, err := cassette.NewRequest(req)
		if err != nil {
			return nil, err
		}

		if r.URL != ia.Request.URL {
			return nil, fmt.Errorf("interaction #%d: got URL %s, want %s", idx, r.URL, ia.Request.URL)
		}

		if r.Method != ia.Request.Method {
			return nil, fmt.Errorf("interaction #%d: got method %s, want %s", idx, r.Method, ia.Request.Method)
		}

		if !bytes.Equal(r.Body, ia.Request.Body) {
			return nil, fmt.Errorf("interaction #%d: got body %s, want %s", idx, string(r.Body), string(ia.Request.Method))
		}

		if ia.Request.Headers.Get("User-Agent") == "" {
			ia.Request.Headers.Set("User-Agent", defaultUserAgent)
		}

		if !maps.EqualFunc(r.Headers, ia.Request.Headers, slices.Equal) {
			return nil, fmt.Errorf("interaction #%d: got headers %s, want %s", idx, r.Headers, ia.Request.Headers)
		}

		idx++
		return &http.Response{
			StatusCode: ia.Response.StatusCode,
			Header:     ia.Response.Headers.Clone(),
			Body:       io.NopCloser(bytes.NewReader(ia.Response.Body)),
		}, nil
	})
}

func TestClient_Interactions(t *testing.T) {
	ctx := t.Context()

	t.Setenv("NOTION_API_KEY", "**************************************************")

	c, err := NewClient(WithHTTPClient(&http.Client{Transport: replay(t)}))
	if err != nil {
		t.Fatal(err)
	}

	if _, err := c.GetPage(ctx, uuid.MustParse("96245c8f-1784-44a4-82ad-1941127c3ec3")); err != nil {
		t.Fatal(err)
	}
}
